version: "3"
services:
  web:
    build: .
    tty: true
    env_file:
      - ./.env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command:
      - npm
      - run
      - serve